### ISSUE TITLE
Update Payment Status enum and logic

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#192]
# Description
We need payment_status under the Invoice model to take in enums instead of a boolean. 

We also need to add automation to update the payment_status

# Todo's
- [x] Change payment_status field to take in the following options:
  - Paid
  - Unpaid
  - Cancelled
- [ ] Add Access control to payment_status mutation. Only receptionists or admins should be able to make this mutation

## Todo's for CX
- [ ] Automatically change payment status from Unpaid to Cancel if the following conditions:
  - Status is "Unpaid"
  - It's been 5 days since status was set to "Unpaid" 
- [ ] Send an email notification if there are 2 days before the 5 days payment deadline

**Comment by dhuangg** [comment]
@jerrylinew can you do a KT session with @tigermli and @NeilAllavarpu covering how to use the notification library + ariflow?

**Comment by tigermli** [comment]
@katiebelleho bump
