### ISSUE TITLE
Add filtering to the “invoices” query

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#193]
# Description
Adding filters to help support the invoice view/find the right invoice

# Todo's
Filter by: 
- [x] creation date (start + end date) 
payment status (Options: “Paid” “Unpaid” “Cancelled”)
- [x] parent / customer (text)
invoice id (text)
- [x] Casting on backend to do fuzzy search on invoice id
- [x] Authenticated user (only show invoices associated with an authenticated parent) 
- [x] Pagination
