### ISSUE TITLE
Tutoring Request Model

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#221]
# Description
This is for the tutoring course request flow where a parent or receptionist submits a request to an instructor + the tutoring center to create a tutoring course. We need a model that contains the course scheduling details, approval status, and content details. 

# Model
- student_id: ID (req)
- course_topic_id: ID (req)
- start_date: Date (req)
- end_date: Date (req)
- days_of_reoccurance: List of DAYS_OF_WEEK options (up to 7) (req)
- duration: Double (req)
- instructor_id
- start_times: List of start times based on days of week. For instance, we want to meet on Weds and Sat. Weds's start time could be 3:00pm and Saturday's start time could be 11:30am
- request_status: enum (SUBMITTED, PENDING_INSTRUCTOR_APPROVAL, PENDING_ADMIN_APPROVAL)
- invoice_setting field:
  - Manual: option for single payment/tutoring sessions purchase
  - Subscription: option for recurring paying/tutoring sessions purchase

<img width="753" alt="Screen Shot 2021-07-06 at 9 12 08 PM" src="https://user-images.githubusercontent.com/12959959/124699021-e0a46000-de9e-11eb-9501-9dd3bc2c242b.png">
<img width="660" alt="Screen Shot 2021-07-06 at 9 16 31 PM" src="https://user-images.githubusercontent.com/12959959/124699330-750ec280-de9f-11eb-9c20-ee39d9fe25d2.png">

# Todo's
- [ ] Create the tutoring_request model
- [ ] Create both tutoringRequest and tutoringRequests queries
- [ ] Create tutoringRequest mutation that accepts all the fields mentioned above
